-- TABELA DE MUNICIPIOS EXPORTADORES
CREATE TABLE IF NOT EXISTS mun_exp (
    CO_ANO INTEGER,
    CO_MES INTEGER,
    SH4 VARCHAR(10),
    CO_PAIS VARCHAR(10),
    SG_UF_MUN VARCHAR(2),
    CO_MUN VARCHAR(10),
    KG_LIQUIDO NUMERIC,
    VL_FOB NUMERIC,
    PRIMARY KEY (CO_ANO, CO_MES, SH4, CO_PAIS, CO_MUN)
);
-- TABELA DE MUNICIPIOS IMPORTADORES
CREATE TABLE IF NOT EXISTS mun_imp (
    CO_ANO INTEGER,
    CO_MES INTEGER,
    SH4 VARCHAR(10),
    CO_PAIS VARCHAR(10),
    SG_UF_MUN VARCHAR(2),
    CO_MUN VARCHAR(10),
    KG_LIQUIDO NUMERIC,
    VL_FOB NUMERIC,
    PRIMARY KEY (CO_ANO, CO_MES, SH4, CO_PAIS, CO_MUN)
);

-- TABELA DE NCMS DE EXPORTAÇÃO
CREATE TABLE IF NOT EXISTS ncm_exp (
    CO_ANO INTEGER,
    CO_MES INTEGER,
    CO_NCM VARCHAR(10),
    CO_UNID VARCHAR(10),
    CO_PAIS VARCHAR(10),
    SG_UF_NCM VARCHAR(2),
    CO_VIA VARCHAR(10),
    CO_URF VARCHAR(10),
    QT_ESTAT NUMERIC,
    KG_LIQUIDO NUMERIC,
    VL_FOB NUMERIC,
    PRIMARY KEY (CO_ANO, CO_MES, CO_NCM, CO_UNID, CO_PAIS, SG_UF_NCM, CO_VIA, CO_URF)
);
-- TABELA DE NCMS DE IMPORTAÇÃO
CREATE TABLE IF NOT EXISTS ncm_imp (
    CO_ANO INTEGER,
    CO_MES INTEGER,
    CO_NCM VARCHAR(10),
    CO_UNID VARCHAR(10),
    CO_PAIS VARCHAR(10),
    SG_UF_NCM VARCHAR(2),
    CO_VIA VARCHAR(10),
    CO_URF VARCHAR(10),
    QT_ESTAT NUMERIC,
    KG_LIQUIDO NUMERIC,
    VL_FOB NUMERIC,
    VL_FRETE NUMERIC,
    VL_SEGURO NUMERIC,
    PRIMARY KEY (CO_ANO, CO_MES, CO_NCM, CO_UNID, CO_PAIS, SG_UF_NCM, CO_VIA, CO_URF)
);

-- TABELA DE NCM VIGENTES
CREATE TABLE IF NOT EXISTS ncm_vigentes (
    CODIGO VARCHAR(10),
    DESCRICAO VARCHAR(1200), -- TEM CARACTRES ESPECIAIS
    DATA_INICIO DATE,
    DATA_FIM DATE,
    TIPO_ATO_INI VARCHAR(9),
    NUMERO_ATO_INI VARCHAR(3),
    ANO_ATO_INI INTEGER,
    PRIMARY KEY (CODIGO, DATA_INICIO, DATA_FIM, NUMERO_ATO_INI, ANO_ATO_INI)
);