-- TABELA DE MUNICIPIOS EXPORTADORES
CREATE TABLE IF NOT EXISTS mun_exp (
    CO_ANO INTEGER,
    CO_MES INTEGER,
    SH4 VARCHAR(10),
    CO_PAIS VARCHAR(10),
    SG_UF_MUN VARCHAR(2),
    CO_MUN VARCHAR(10),
    KG_LIQUIDO NUMERIC,
    VL_FOB NUMERIC
);
-- TABELA DE MUNICIPIOS IMPORTADORES
CREATE TABLE IF NOT EXISTS mun_imp (
    CO_ANO INTEGER,
    CO_MES INTEGER,
    SH4 VARCHAR(10),
    CO_PAIS VARCHAR(10),
    SG_UF_MUN VARCHAR(2),
    CO_MUN VARCHAR(10),
    KG_LIQUIDO NUMERIC,
    VL_FOB NUMERIC
);

-- TABELA DE NCMS DE EXPORTAÇÃO
CREATE TABLE IF NOT EXISTS ncm_exp (
    CO_ANO INTEGER,
    CO_MES INTEGER,
    CO_NCM VARCHAR(10),
    CO_UNID VARCHAR(10),
    CO_PAIS VARCHAR(10),
    SG_UF_NCM VARCHAR(2),
    CO_VIA VARCHAR(10),
    CO_URF VARCHAR(10),
    QT_ESTAT NUMERIC,
    KG_LIQUIDO NUMERIC,
    VL_FOB NUMERIC
);
-- TABELA DE NCMS DE IMPORTAÇÃO
CREATE TABLE IF NOT EXISTS ncm_exp (
    CO_ANO INTEGER,
    CO_MES INTEGER,
    CO_NCM VARCHAR(10),
    CO_UNID VARCHAR(10),
    CO_PAIS VARCHAR(10),
    SG_UF_NCM VARCHAR(2),
    CO_VIA VARCHAR(10),
    CO_URF VARCHAR(10),
    QT_ESTAT NUMERIC,
    KG_LIQUIDO NUMERIC,
    VL_FOB NUMERIC,
    VL_FRETE NUMERIC,
    VL_SEGURO NUMERIC
);

-- TABELA DE NCM VIGENTES
CREATE TABLE IF NOT EXISTS ncm_ok (
    CO_NCM VARCHAR(10),
    DESCRICAO VARCHAR(1157),
    DAT_INI DATE,
    DAT_FIM DATE,
    TIP_ATO_INI VARCHAR(9),
    NUM_ATO_INI VARCHAR(3),
    ANO_ATO_INI INTEGER
);